name: Build and Publish Dart Project

on:
  push:
    branches:
      - main  # ou o nome da branch que você deseja
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Dart Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Dart
        uses: dart-lang/setup-dart@v2

      - name: Install dependencies
        run: dart pub get

      - name: Build project
        run: dart compile exe bin/main.dart -o build/my_project

      - name: Prepare artifact
        run: |
          mkdir -p build/artifact
          cp build/my_project build/artifact/my_project

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dart-project-binary
          path: build/artifact/my_project
